### ISSUE TITLE
smach_viewer on Kinetic

### ISSUE THREAD

**Issue by JimmyDaSilva** [ros-visualization/executive_smach_visualization#13]
I have been looking at the various forks( @jbohren 's as well)  to find a way to run the smach_viewer on Kinetic but without success.
I know you guys are struggling with the new version of wxPython and xdot.

Whether it runs on the new coming rqt plugin or not, I would love to know if someone succeeded in running a viewer for smach on Kinetic.

Keep on the great work!

**Comment by matt3o** [comment]
Have a look at the document I just created - I found a way to make rqt_smach work in ROS Kinetic: https://gist.github.com/matt3o/88bced95dba37a8932a51904d0734dff
Any feedback is highly appreciated!

Also I'd love to merge this to a new kinetic-devel branch but all recent PRs were ignored..

**Comment by vincentrou** [comment]
How can we go forward on this ?
@k-okada Are still thinking about releasing it for kinetic ?

**Comment by k-okada** [comment]
I think it's already released ;-)
https://github.com/ros/rosdistro/pull/15288
http://repositories.ros.org/status_page/ros_kinetic_default.html?q=smach

--
◉ Kei Okada


2017-09-06 18:49 GMT+09:00 vincentrou <notifications@github.com>:

**Comment by vincentrou** [comment]
You are right, thank you.
I was looking for rqt_smach but smach_viewer is fine for now.
So I think we can close this issue.
