### ISSUE TITLE
Cannot start smach_viewer.py in launch file

### ISSUE THREAD

**Issue by StephanHasler** [ros-visualization/executive_smach_visualization#17]
I can start smach_viewer like:
`rosrun smach_viewer smach_viewer.py`

I like to start it as a node inside a launch file like: 
`<node pkg="smach_viewer" name="smach_viewer" type="smach_viewer.py"/>`

However I always get following error message:
```
usage: smach_viewer.py [-h] [-f]
smach_viewer.py: error: unrecognized arguments: __name:=smach_viewer_1 __log:=/tmp/ros_stephanh/7f335adc-a762-11e7-9444-0cc47ae2606c/smach_viewer_1-4.log
[smach_viewer_1-4] process has died [pid 30266, exit code 2, cmd /hri/localdisk/stephanh/care_ros_ws/src/executive_smach_visualization/smach_viewer/scripts/smach_viewer.py __name:=smach_viewer_1 __log:=/tmp/ros_stephanh/7f335adc-a762-11e7-9444-0cc47ae2606c/smach_viewer_1-4.log].                       
log file: /tmp/ros_stephanh/7f335adc-a762-11e7-9444-0cc47ae2606c/smach_viewer_1-4*.log 
```

I think this is because the ROS remapping arguments are not removed from sys.argv before argparsing. A solution that worked for me is following code inside smach_viewer.py

```
if __name__ == '__main__':
    rospy.init_node('smach_viewer', argv=sys.argv, anonymous=False, disable_signals=True, log_level=rospy.INFO)
    sys.argv = rospy.myargv(argv=sys.argv)

    main()
```

However, I am not sure if this is the correct way to do it.

**Comment by k-okada** [comment]
Hi
We have similar report and have pending PullRequest at  https://github.com/ros-visualization/executive_smach_visualization/pull/16. It seems slightly different than your solution.
If #16 is ok for you, please add more +1 to the PR threads, if that is not works for you. Please give us a feedback.

Thanks
