### ISSUE TITLE
smach_viewer on Melodic

### ISSUE THREAD

**Issue by Patrick-Lascombe** [ros-visualization/executive_smach_visualization#20]
Hello,

I followed the tutorial for learning smach but when it came to visualize the state machine by running `rosrun smach_viewer smach_viewer.py`. I have this errors that appears : 

```
wxversion 2.8 is not installed, installed versions are ['3.0-gtk3']
Gtk-Message: 11:47:05.233: Failed to load module "canberra-gtk-module"
wxversion 2.8 is not installed, installed versions are ['3.0-gtk3']

(smach_viewer.py:1744): GLib-GObject-WARNING **: 11:47:05.887: cannot register existing type 'GdkDisplayManager'

(smach_viewer.py:1744): GLib-CRITICAL **: 11:47:05.887: g_once_init_leave: assertion 'result != 0' failed

(smach_viewer.py:1744): GLib-GObject-CRITICAL **: 11:47:05.887: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

Do you know why I receive this error and how to fix it ?

Thanks for your help

**Comment by k-okada** [comment]
please check if my `melodic-devel` package works https://github.com/k-okada/executive_smach_visualization/commits/melodic-devel

note that do not forget to run `rosdep install ....`, which depends on  https://github.com/ros/rosdistro/pull/19652 at this moment.

**Comment by corot** [comment]
Hi! same issue here. @k-okada, I have tried your fork and at least doesn't crash. Thanks!
But I found some other problems. I get the following WARNs:
![image](https://user-images.githubusercontent.com/322610/54787004-bcb7a480-4c2a-11e9-937e-a732fbf5ed8b.png)

and them the FSM appearance is very weird:
![image](https://user-images.githubusercontent.com/322610/54786957-98f45e80-4c2a-11e9-9428-02450514e4e5.png)

Also, for a ROS node you should handle the arguments passed by roslaunch; otherwise you get:

`
usage: smach_viewer.py [-h] [-f]
smach_viewer.py: error: unrecognized arguments: __name:=object_manip_smach_viewer __log:=/home/jorge/.ros/log/59d8bcc2-4c21-11e9-a555-bc5ff4f7bec8/object_manip_smach_viewer-36.log
`

**Comment by spuetz** [comment]
@k-okada Any plan for a pull request? Would be nice to have a running version released.

**Comment by k-okada** [comment]
Could someone fix the warnings and problems reported on https://github.com/ros-visualization/executive_smach_visualization/issues/20#issuecomment-475415324 ?

**Comment by twdragon** [comment]
Found a workaround using [this fork](https://github.com/k-okada/executive_smach_visualization) on melodic branch. Also there is needed to install `python-gi-cairo` package which is not installed by default for python2 in Ubuntu 18.04

**Comment by corot** [comment]
> Found a workaround using [this fork](https://github.com/k-okada/executive_smach_visualization) on melodic branch. Also there is needed to install `python-gi-cairo` package which is not installed by default for python2 in Ubuntu 18.04

That's the fork/branch I'm using, and I still get the weird appearance I posted before. Do you see the FSM with normal aspect?

**Comment by ekorudiawan** [comment]
How to install in melodic?

**Comment by k-okada** [comment]
> I still get the weird appearance I posted before. 

Let me clear that the graph itself is not wrong, I guess graph itself is ok, just we do not like the appearance. Something has been changed between 0.6 and 0.9 of xdot (
https://gitlab.com/graphviz/graphviz/issues/1485)

I tried to fix by https://github.com/ros-visualization/executive_smach_visualization/commit/d10d0152426c4641885412eb525a8d10124e674f, but not sure if this is ok

**Comment by Combinacijus** [comment]
Applied this fix https://github.com/ros-visualization/executive_smach_visualization/commit/d10d0152426c4641885412eb525a8d10124e674f from @k-okada and now it's way nicer
Before:
![image](https://user-images.githubusercontent.com/16375702/92309999-ae8e4d00-efb2-11ea-92ff-bf40673175ba.png)
After:
![image](https://user-images.githubusercontent.com/16375702/92309984-93234200-efb2-11ea-80f3-b9c841fdab4f.png)

**Comment by k-okada** [comment]
@Combinacijus thanks for feedback , you can use https://github.com/ros-visualization/executive_smach_visualization/commit/d10d0152426c4641885412eb525a8d10124e674f from our `melodic-devel` branch (https://github.com/ros-visualization/executive_smach_visualization/commits/melodic-devel)

Unfortunately, I do not have permission to change default branch , @wjwwood @tfoote could you change the default branch from `indigo-devel` to `melodic-branch` ?

**Comment by wjwwood** [comment]
@k-okada done, also I invited you to the github team so you can administer further if needed.

**Comment by k-okada** [comment]
\@wjwwood thank you!
