### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by Timple** [ros-visualization/executive_smach_visualization#29]
Would you mind releasing these packages also for the newest distribution ROS Noetic? :)

**Comment by Carlbouakl** [comment]
Still doesn't run on noetic right?

**Comment by Timple** [comment]
Nope

**Comment by karl-exwzd** [comment]
A non-ideal solution exists: https://github.com/ros-visualization/executive_smach_visualization/issues/34#issuecomment-870147946

**Comment by martinerk0** [comment]
Can confirm that @InigoMoreno 's PR https://github.com/ros-visualization/executive_smach_visualization/pull/39 works on 20.04 and Noetic.

I downloaded it from his repo and installed dependencies in these PR's.
`git clone https://github.com/InigoMoreno/executive_smach_visualization.git --branch noetic-devel --single-branch`

**Comment by k-okada** [comment]
done, https://github.com/ros/rosdistro/pull/33940
Please check once deb is available

**Comment by mikaelarguedas** [comment]
Thanks @k-okada for working on this!
I tried the deb but it pulls a bunch of python2 deps and doesnt run on python 3
```
/usr/bin/env: ‘python’: No such file or directory
```
But loads of other errors if shebang modified for Python 3.

The version of https://github.com/ros-visualization/executive_smach_visualization/pull/39 works for me :+1: 

Would it be possible to create a noetic-devel branch and release that version on it ? (happy to help do that if going that route seems ok)

**Comment by k-okada** [comment]
@mikaelarguedas thaks for checking, and I have forget to update `package.xml`, I also used `catkin_install_python` to support shbang to Python3, see #43 
I personally prefer to keep one branch for both melodic/noetic, because most of our robot system using Melodic
