### ISSUE TITLE
catkinize for hydro

### ISSUE THREAD

**Issue by jbohren** [ros-visualization/executive_smach_visualization#3]

**Comment by 130s** [comment]
[Pull requested](https://github.com/ros-visualization/executive_smach_visualization/pull/4) for `groovy-devel` branch.

**Comment by jbohren** [comment]
Unless someone else has time to work on this, I don't think rqt_smach is going to be ready for hydro, regardless.

**Comment by 130s** [comment]
@jbohren I can't guarantee but I'm willing to give it a try unless there's another ones.

**Comment by furushchev** [comment]
catkinized https://github.com/ros-visualization/executive_smach_visualization/pull/10
